#!/bin/bash
echo "=========================================="
echo "启动内网穿透..."
echo "=========================================="
echo ""
echo "请在新的终端窗口运行以下命令："
echo ""
echo "  ssh -R 80:localhost:8080 serveo.net"
echo ""
echo "或者使用 localhost.run："
echo ""
echo "  ssh -R 80:localhost:8080 localhost.run"
echo ""
echo "运行后会显示一个公网URL，如："
echo "  https://xxxx.serveo.net"
echo ""
echo "手机访问该URL即可"
echo "=========================================="
